name: Vulnerable Kubernetes CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          mv ./kind /usr/local/bin/kind

      - name: Create Kubernetes Cluster
        run: |
          kind create cluster --name goat-cluster
          export KUBECONFIG="$(kind get kubeconfig-path --name="goat-cluster")"
          kubectl get nodes

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          mv ./kubectl /usr/local/bin/kubectl

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Clone Kubernetes Goat Repository
        run: |
          git clone https://github.com/madhuakula/kubernetes-goat.git

      - name: List Directory Contents to Confirm Clone
        run: |
          ls -al

      - name: Install Kyverno using Helm
        run: |
          helm repo add kyverno https://kyverno.github.io/kyverno/
          helm repo update
          helm install kyverno kyverno/kyverno --namespace kyverno --create-namespace


      - name: Validate Helm Templates
        run: |
          cd kubernetes-goat/scenarios/metadata-db
          helm lint .

      - name: Deploy Metadata-db Using Helm
        run: |
          cd kubernetes-goat/scenarios/metadata-db
          helm install metadata-db .

      - name: Deploy Kubernetes Goat Using Manifests Recursively (Excluding Metadata-db)
        run: |
          cd kubernetes-goat
          find scenarios/ -type f \( -name '*.yaml' -o -name '*.yml' \) ! -path 'scenarios/metadata-db/*' -print0 | while IFS= read -r -d '' file; do
            kubectl apply -f "$file"
          done
          kubectl get pods -A
      
      - name: Verify Deployment
        run: |
          kubectl get services -A
          kubectl get pods -A
        
     - name: Scan YAML Manifests with kube-score (SAST)
        run: |
          docker run --rm -v $(pwd)/kubernetes-goat/scenarios:/scenarios zegl/kube-score:latest score /scenarios/*.yaml > kube-score-report.txt

      - name: Scan Container Images with Trivy (SCA)
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/trivy-cache:/root/.cache/ aquasecurity/trivy:latest image madhuakula/kubernetes-goat:latest --severity HIGH,CRITICAL --format json --output trivy-report.json

      - name: Run Kube-bench for CIS Benchmark
        run: |
          docker run --rm -v $(pwd)/cfg:/cfg aquasecurity/kube-bench:latest --json > kube-bench-report.json

      - name: Monitor Runtime Security with Falco
        run: |
          docker run --rm --privileged falcosecurity/falco:latest

      - name: Use Tetragon for eBPF-based Monitoring
        run: |
          docker run --rm --privileged cilium/tetragon:latest

      - name: Upload Reports
        uses: actions/upload-artifact@v3
        with:
          name: security-reports
          path: |
            kube-score-report.txt
            trivy-report.json
            kube-bench-report.json
